if(NOT DEFINED CLI OR NOT DEFINED TEST_DIR)
  message(FATAL_ERROR "CLI and TEST_DIR required")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}")
function(check_failure expected)
  execute_process(COMMAND "${CLI}" ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(result EQUAL 0 OR NOT err MATCHES "${expected}")
    message(FATAL_ERROR "Expected failure matching ${expected}; result=${result}; stdout=${out}; stderr=${err}")
  endif()
endfunction()
execute_process(COMMAND "${CLI}" --help RESULT_VARIABLE result OUTPUT_VARIABLE help)
if(NOT result EQUAL 0 OR NOT help MATCHES "--highlights")
  message(FATAL_ERROR "Missing processing help")
endif()
check_failure("required" --input absent --output "${TEST_DIR}/never.png")
foreach(value nan inf 1junk 21 -21)
  check_failure("EV" --input absent --output "${TEST_DIR}/never.png" --highlights preserve --ev "${value}")
endforeach()
foreach(value -0.1 1.1 nan 1junk)
  check_failure("tone" --input absent --output "${TEST_DIR}/never.png" --highlights preserve --tone-strength "${value}")
endforeach()
check_failure("duplicate" --input absent --input other --output out --highlights preserve)
check_failure("unknown" --unknown x)
check_failure("missing" --input)
check_failure("highlights" --input absent --output out --highlights invalid)
check_failure("unknown" --version --histogram)
if(EXISTS "${TEST_DIR}/never.png")
  message(FATAL_ERROR "Invalid invocation created output")
endif()
